### ISSUE TITLE
problem with encoding in result of `read_mow_data()`

### ISSUE THREAD

**Issue by hansvancalster** [inbo/inborutils#103]
Running the example for `read_mow_data()` from the vignette suggests encoding problems:

![image](https://user-images.githubusercontent.com/18713718/110305716-4968f200-7ffd-11eb-9e14-1a34a723c786.png)

Maybe something to discuss with @inbo/bmk

_Originally posted by @hansvancalster in https://github.com/inbo/inborutils/issues/102#issuecomment-792637091_

**Comment by ElsLommelen** [comment]
Looks like an encoding problem.  Some possible solutions:
- I haven't looked at it into detail, but maybe this `ISO-8859-15` is not the right one to use in a Windows environment?  `?file` gives an elaborate explanation on encodings in different OS, maybe this helps?
- Does this encoding problem show up in all output, or only in this table?  (Some characters are not displayed correctly in R, but they are correctly interpreted and will be displayed correctly in for instance Rmd-outputs.)
- Another problem could be that the `.txt` file was not saved in the expected format.  When generating and writing a `.csv` file in R, I often get similar problems when I want to read it again in UTF-8 format.  What helps in this case, is open the text file in Notepad++, specify the intended encoding (or convert to the intended encoding and/or make sure the characters are displayed correctly) and save it as such.  After that, I could perfectly read the file without encoding problems, at least in my case.
