### ISSUE TITLE
download_knmi_data_hour {inborutils} not downloading weather data

### ISSUE THREAD

**Issue by ghost** [inbo/inborutils#108]
After requesting a download for weather data I receive this .txt:

(from the example: 
download_knmi_data_uur(c(310, 319), "PRCP", "2011-01-01", "2012-02-17",output_file = "knmi_output_download.txt") 
which btw has to be changed from uur to hour)

<!DOCTYPE html>

  <html class="no-js" lang="nl">

<head>
  <meta charset="utf-8" />
  <title>KNMI - Klimatologie</title>
  <meta name="description" content="">
  <meta name="author" content="" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="shortcut icon" href="https://cdn.knmi.nl/assets/favicon-06dd94e551015e92293dd6d7525ab5c1ab9a51f68bebdf0b4669c12d69dbe522.ico" />
  <link rel="apple-touch-icon" href="https://cdn.knmi.nl/assets/apple-touch-icon-220a47425fd62d44dc04800d3067032801342cd842cc7935b89dbca0cec4a7c9.png" />
  <link rel="stylesheet" media="all" href="https://cdn.knmi.nl/assets/application-6931331cf59bf7a56417431ea109a5e2dbcd9d116736830f5e872278fd229e36.css" data-turbolinks-track="true" />
  <script src="https://cdn.knmi.nl/assets/modernizr/modernizr.min-61c5cef44c1ccbcd872b5a6eacda768c609564a4b1008880c84b85477a0954e0.js" data-turbolinks-track="true"></script>
  
  
  <meta name="csrf-param" content="authenticity_token" />
<meta name="csrf-token" content="mNdmM9VkYLiV9iNGdsSEe/0WzWJ3En77z/VX5Y0OOfSzl6Zl9oIvRYom7ErKNG/oR/6PTvXgYDP+dDl0xds9GA==" />

</head>
<body data-no-turbolink="true" class=" ">

<a tabindex="0" id="skiplink" href="#mainBody">translation missing: nl.to_main_content</a>

	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-60727058-1', 'auto');
	  ga('set', 'forceSSL', true); // Toelichting CBP: Gebruik altijd https voor Google Analytics
	  ga('set', 'anonymizeIp', true); // Toelichting CBP: Zet de IP-maskering aan
 	  ga('send', 'pageview');

	</script>

<header class="site-header">
  <div class="wrapper relative">
    <div class="site-header__logowrp">
      <a href="/home">
        <img src="data:image/gif;base64,R0lGODlhEAAJAPAAAP///wAAACH/C1hNUCBEYXRhWE1QAz94cAAh+QQFAAAAACwAAAAAEAAJAAACCoSPqcvtD6OclBUAOw==" class="b-lazy site-header__logo" data-src="https://cdn.knmi.nl/assets/logo_large-a9be0e49aed0aa1f72a7da54d348d14ce94d070e7950f67dbc85039f0574ca48.png" data-src-xs="https://cdn.knmi.nl/assets/logo_small-849785d90ac219aeb491d194cd34d24ee69bdc0253d3ea24d3352c8edcbb6acf.png" alt="Logo Koninklijk Nederlands Meteorologisch Instituut | Ministerie van Infrastructuur en Waterstaat" />
        <noscript>
          <img class="site-header__logo" width="230" height="79" alt="Logo KNMI" src="https://cdn.knmi.nl/assets/logo_large-a9be0e49aed0aa1f72a7da54d348d14ce94d070e7950f67dbc85039f0574ca48.png" />
        </noscript>
      </a>
    </div>
    <div class="site-header__meta">
      <a href="/over-het-knmi/about">English</a>
      <a data-active="normaal contrast" data-inactive="hoog contrast" class="highcontrast-toggle hidden" href="#"></a>
    </div>
  </div>
  <div class="wrapper--navbar">
    <div class="main-navbar is-loading">
        <nav>
          <ul>
              <li>
                <a class="" href="/home" target="">
                  Home
                  
                </a>
              </li>
              <li>
                <a class="is-active" href="/nederland-nu/weer" target="">
                  Nederland nu
                  <span class="nav-toggle icon-arrow-small-down"></span>
                </a>
                  <ul>
                      <li><a class="" href="/nederland-nu/weer">Weer</a></li>
                      <li><a class="" href="/nederland-nu/seismologie">Seismologie</a></li>
                      <li><a class="" href="/nederland-nu/maritiem">Maritiem</a></li>
                      <li><a class="" href="/nederland-nu/luchtvaart">Luchtvaart</a></li>
                      <li><a class="is-active" href="/nederland-nu/klimatologie">Klimatologie</a></li>
                      <li><a class="" href="/nederland-nu/weer/waarschuwingen-en-verwachtingen/caribisch-nederland">Caribisch Nederland</a></li>
                  </ul>
              </li>
              <li>
                <a class="" href="/klimaat" target="">
                  Klimaat
                  
                </a>
              </li>
              <li>
                <a class="" href="/producten-en-diensten" target="">
                  Producten &amp; diensten
                  
                </a>
              </li>
              <li>
                <a class="" href="/kennis-en-datacentrum" target="">
                  Kennis &amp; uitleg
                  
                </a>
              </li>
              <li>
                <a class="" href="/research" target="">
                  Research
                  
                </a>
              </li>
              <li>
                <a class="" href="/over-het-knmi/over" target="">
                  Over het KNMI
                  <span class="nav-toggle icon-arrow-small-down"></span>
                </a>
                  <ul>
                      <li><a class="" href="/over-het-knmi/over">Over het KNMI</a></li>
                      <li><a class="" href="/over-het-knmi/bestuur">Bestuur</a></li>
                      <li><a class="" href="/over-het-knmi/kerntaken">Kerntaken</a></li>
                      <li><a class="" href="/over-het-knmi/KNMI-werkt-internationaal">Internationaal</a></li>
                      <li><a class="" href="/over-het-knmi/vacatures">Werken bij</a></li>
                      <li><a class="" href="/over-het-knmi/nieuws">Nieuws</a></li>
                      <li><a class="" href="/over-het-knmi/agenda">Agenda</a></li>
                      <li><a class="" href="/over-het-knmi/contact/contactformulier">Contact</a></li>
                  </ul>
              </li>
          </ul>
        </nav>
      <form class="main-navbar__search" autocomplete="off" method="GET" action="/zoeken">
        <fieldset>
          <legend class="main-navbar__search-legend">Zoek binnen de site</legend>
          <div class="main-navbar__search-context">
            <input id="context_search" type="radio" name="context" value="/zoeken" />
            <label for="context_search"><span>binnen de hele site</span></label>
            <input id="context_data_center" type="radio" name="context" value="/kennis-en-datacentrum/zoekresultaten" />
            <label for="context_data_center"><span>binnen het kennis- &amp; datacentrum</span></label>
          </div>
          <label class="main-navbar__search-label" for="q">Trefwoord</label>
          <input type="text" id="q" name="q" placeholder="Zoeken" />
          <button class="icon-search" type="submit"><span>Zoek</span></button>
        </fieldset>
      </form>
      <a class="icon-menu main-navbar__toggle" href="#">Menu</a>
    </div>
    <div class="main-navbar__sub is-loading"></div>
  </div>
</header>

<div class="nav-overlay">
  <a href="#" class="main-navbar__close icon-close">Sluiten</a>
  <div class="nav-overlay__inner"></div>
</div>

<main id="mainBody" tabindex="0"  lang=nl>
  
<div class="wrapper js_breadcrumb ">
  <div class="weather-small">
  <a href="/nederland-nu/weer/waarschuwingen" class="weather-small__alert weather-small--green">
      Code groen
  </a>
</div>
    <ul class="breadcrumb">
        <li><a class="" href="/">Home</a></li>
        <li><a class="" href="/nederland-nu/weer">Nederland nu</a></li>
      	<li>Klimatologie</li>
  </ul>

</div>

<div class="wrapper">
  <div class="columns filled-main-content">
    <div class="col-sm-12 col-md-10 col-md-offset-1">
      <h1 class="color-blue">Klimatologie</h1>
      <div class="filled-main-content__highlight media">
          <div class="media__img weather__image weather__image--forecast">
            <figure>
              <a class="figure__link" href="//cdn.knmi.nl/knmi/map/page/klimatologie/geografische-overzichten/prec/prec.png">
                <img src="//cdn.knmi.nl/knmi/map/page/klimatologie/geografische-overzichten/prec/prec.png" alt="Neerslagsommen, gisteren">
              </a>
            </figure>
          </div>
          <div class="media__body editable-table">
            <h2>Klimatologie - Informatie over weer in het verleden</h2>

<p>Het&nbsp;KNMI is verantwoordelijk voor de archivering van alle weermetingen in Nederland. Via deze overzichtspagina heeft u toegang tot de gevalideerde gegevens in de vorm van tijdreeksen van metingen, grafieken, kaarten en overzichten.&nbsp;</p>

<ul>
	<li><a href="/nederland-nu/klimatologie-metingen-en-waarnemingen">Metingen &amp; Waarnemingen</a></li>
	<li><a href="/nederland-nu/klimatologie-kaarten-en-grafieken">Kaarten &amp; Grafieken</a></li>
	<li><a href="/nederland-nu/klimatologie-overzichten">Overzichten</a></li>
	<li><a href="/nederland-nu/klimatologie/lijsten">Ranglijsten</a></li>
</ul>

            <div class="share ">
	<span class="share__title">Delen via</span>
	<ul class="share__list">
		<li><a href="https://www.facebook.com/sharer/sharer.php?u=http://www.knmi.nl/nederland-nu/klimatologie" class="share__button facebook icon-facebook">Facebook</a></li>
		<li><a href="https://twitter.com/home?status=http://www.knmi.nl/nederland-nu/klimatologie" class="share__button twitter icon-twitter">Twitter</a></li>
		<li><a href="https://www.linkedin.com/shareArticle?mini=true&url=http://www.knmi.nl/nederland-nu/klimatologie" class="share__button linkedin icon-linkedin">Linkedin</a></li>
		<li><a href="whatsapp://send" class="wa_btn wa_btn_s" data-text="Kijk eens naar deze pagina:" data-href="" style="display:none">WhatsApp</a></li>
	</ul>
</div>

<script type="text/javascript">if(typeof wabtn4fg==="undefined"){wabtn4fg=1;h=document.head||document.getElementsByTagName("head")[0],s=document.createElement("script");s.type="text/javascript";s.src="/knmi/js/whatsapp-sharing/whatsapp-button.js";h.appendChild(s);}</script>
          </div>
      </div>
    </div>
  </div>
</div>

  <div class="wrapper">
      <div class="morelinks columns">
    <div class="col-sm-12 col-md-10 col-md-offset-1">
      <h2 class="morelinks__title">Meer informatie over dit onderwerp</h2>
      <ul>
            <li><a class="btn is-external" href="https://www.knmidata.nl/" target="_blank">KNMI Dataplatform (KDP)</a></li>
            <li><a class="btn is-external" href="http://climexp.knmi.nl/selectdailyfield2.cgi?id=someone@somewhere" target="_blank">KNMI Climate Explorer </a></li>
      </ul>
    </div>
  </div>

  </div>

</main>

<footer class="site-footer">
  <ul>
    <li><a href="/copyright">Copyright</a></li>
    <li><a href="/privacy">Privacy</a></li>

    <li><a href="/cookies">Cookies</a></li>
    <li><a href="/toegankelijkheid">Toegankelijkheid</a></li>
  </ul>
</footer>

<div class="loading-modal"></div>

<script src="https://cdn.knmi.nl/assets/application-5e620dff4e12d283fd32eda30fe096b44eaf4ba129e7aa17154a36e18df7a615.js" data-turbolinks-track="true"></script>

</body>
</html>

**Comment by hansvancalster** [comment]
Thanks for reporting! Looks like a bug. We will investigate the problem. Running the example returns an error in `curl::curl_fetch_memory()`

``` r
library(inborutils)
download_knmi_data_hour(stations = c(310, 319),
                        variables =  "PRCP",
                        start_date =  "2011-01-01",
                        end_date =  "2012-02-17",
                        output_file = "knmi_output_download.txt")
#> Error in curl::curl_fetch_memory(url, handle = handle): Failure when receiving data from the peer
```

<sup>Created on 2021-03-09 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

<details style="margin-bottom:10px;">

<summary>Session info</summary>

``` r
sessioninfo::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.0.2 (2020-06-22)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  Dutch_Belgium.1252          
#>  ctype    Dutch_Belgium.1252          
#>  tz       Europe/Paris                
#>  date     2021-03-09                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version date       lib source        
#>  assertable    0.2.8   2021-01-27 [1] CRAN (R 4.0.4)
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.3)
#>  bit           4.0.4   2020-08-04 [1] CRAN (R 4.0.4)
#>  bit64         4.0.5   2020-08-30 [1] CRAN (R 4.0.4)
#>  blob          1.2.1   2020-01-20 [1] CRAN (R 4.0.3)
#>  cachem        1.0.4   2021-02-13 [1] CRAN (R 4.0.4)
#>  class         7.3-17  2020-04-26 [2] CRAN (R 4.0.2)
#>  classInt      0.4-3   2020-04-07 [1] CRAN (R 4.0.4)
#>  cli           2.3.1   2021-02-23 [1] CRAN (R 4.0.2)
#>  colorspace    2.0-0   2020-11-11 [1] CRAN (R 4.0.3)
#>  conditionz    0.1.0   2019-04-24 [1] CRAN (R 4.0.4)
#>  crayon        1.4.1   2021-02-08 [1] CRAN (R 4.0.3)
#>  crosstalk     1.1.1   2021-01-12 [1] CRAN (R 4.0.3)
#>  curl          4.3     2019-12-02 [1] CRAN (R 4.0.3)
#>  data.table    1.14.0  2021-02-21 [1] CRAN (R 4.0.4)
#>  DBI           1.1.1   2021-01-15 [1] CRAN (R 4.0.3)
#>  digest        0.6.27  2020-10-24 [1] CRAN (R 4.0.3)
#>  dplyr         1.0.4   2021-02-02 [1] CRAN (R 4.0.3)
#>  e1071         1.7-4   2020-10-14 [1] CRAN (R 4.0.4)
#>  ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.3)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.0.3)
#>  fansi         0.4.2   2021-01-15 [1] CRAN (R 4.0.3)
#>  fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.0.4)
#>  fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.3)
#>  generics      0.1.0   2020-10-31 [1] CRAN (R 4.0.3)
#>  ggplot2       3.3.3   2020-12-30 [1] CRAN (R 4.0.3)
#>  gh            1.2.0   2020-11-27 [1] CRAN (R 4.0.4)
#>  glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.3)
#>  gtable        0.3.0   2019-03-25 [1] CRAN (R 4.0.3)
#>  highr         0.8     2019-03-20 [1] CRAN (R 4.0.3)
#>  hms           1.0.0   2021-01-13 [1] CRAN (R 4.0.3)
#>  htmltools     0.5.1.1 2021-01-22 [1] CRAN (R 4.0.3)
#>  htmlwidgets   1.5.3   2020-12-10 [1] CRAN (R 4.0.3)
#>  httr          1.4.2   2020-07-20 [1] CRAN (R 4.0.3)
#>  inborutils  * 0.1.2   2021-03-09 [1] local         
#>  iterators     1.0.13  2020-10-15 [1] CRAN (R 4.0.4)
#>  jsonlite      1.7.2   2020-12-09 [1] CRAN (R 4.0.3)
#>  KernSmooth    2.23-17 2020-04-26 [2] CRAN (R 4.0.2)
#>  knitr         1.31    2021-01-27 [1] CRAN (R 4.0.3)
#>  lattice       0.20-41 2020-04-02 [2] CRAN (R 4.0.2)
#>  lazyeval      0.2.2   2019-03-15 [1] CRAN (R 4.0.3)
#>  leaflet       2.0.4.1 2021-01-07 [1] CRAN (R 4.0.4)
#>  lifecycle     1.0.0   2021-02-15 [1] CRAN (R 4.0.4)
#>  lubridate     1.7.9.2 2020-11-13 [1] CRAN (R 4.0.3)
#>  magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.0.3)
#>  memoise       2.0.0   2021-01-26 [1] CRAN (R 4.0.4)
#>  munsell       0.5.0   2018-06-12 [1] CRAN (R 4.0.3)
#>  oai           0.3.0   2019-09-07 [1] CRAN (R 4.0.4)
#>  odbc          1.3.0   2020-10-27 [1] CRAN (R 4.0.4)
#>  pillar        1.5.0   2021-02-22 [1] CRAN (R 4.0.2)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.3)
#>  plyr          1.8.6   2020-03-03 [1] CRAN (R 4.0.4)
#>  ps            1.5.0   2020-12-05 [1] CRAN (R 4.0.3)
#>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.3)
#>  R6            2.5.0   2020-10-28 [1] CRAN (R 4.0.3)
#>  Rcpp          1.0.6   2021-01-15 [1] CRAN (R 4.0.3)
#>  readr         1.4.0   2020-10-05 [1] CRAN (R 4.0.3)
#>  reprex        1.0.0   2021-01-27 [1] CRAN (R 4.0.3)
#>  rgbif         3.5.2   2021-01-27 [1] CRAN (R 4.0.4)
#>  rlang         0.4.10  2020-12-30 [1] CRAN (R 4.0.3)
#>  rmarkdown     2.7     2021-02-19 [1] CRAN (R 4.0.2)
#>  RSQLite       2.2.3   2021-01-24 [1] CRAN (R 4.0.4)
#>  rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.0.3)
#>  scales        1.1.1   2020-05-11 [1] CRAN (R 4.0.3)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.3)
#>  sf            0.9-7   2021-01-06 [1] CRAN (R 4.0.4)
#>  sp            1.4-5   2021-01-10 [1] CRAN (R 4.0.4)
#>  stringi       1.5.3   2020-09-09 [1] CRAN (R 4.0.3)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.0.3)
#>  tibble        3.0.6   2021-01-29 [1] CRAN (R 4.0.3)
#>  tidyr         1.1.2   2020-08-27 [1] CRAN (R 4.0.3)
#>  tidyselect    1.1.0   2020-05-11 [1] CRAN (R 4.0.3)
#>  units         0.7-0   2021-02-25 [1] CRAN (R 4.0.4)
#>  utf8          1.1.4   2018-05-24 [1] CRAN (R 4.0.3)
#>  uuid          0.1-4   2020-02-26 [1] CRAN (R 4.0.3)
#>  vctrs         0.3.6   2020-12-17 [1] CRAN (R 4.0.3)
#>  wellknown     0.7.2   2021-01-07 [1] CRAN (R 4.0.4)
#>  whisker       0.4     2019-08-28 [1] CRAN (R 4.0.3)
#>  withr         2.4.1   2021-01-26 [1] CRAN (R 4.0.3)
#>  wk            0.3.4   2021-01-16 [1] CRAN (R 4.0.4)
#>  xfun          0.21    2021-02-10 [1] CRAN (R 4.0.3)
#>  xml2          1.3.2   2020-04-23 [1] CRAN (R 4.0.4)
#>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.3)
#> 
#> [1] C:/R/library
#> [2] C:/Program Files/R/R-4.0.2/library
```

</details>

**Comment by hansvancalster** [comment]
https://www.knmi.nl/kennis-en-datacentrum/achtergrond/data-ophalen-vanuit-een-script

The service appears to be down:
![image](https://user-images.githubusercontent.com/18713718/110514775-efa11e80-8107-11eb-8ccf-39c06fc98724.png)
