### ISSUE TITLE
Function `gbif_species_name_match` unnecessary

### ISSUE THREAD

**Issue by damianooldoni** [inbo/inborutils#120]
[inborutils::gbif_species_name_match](https://inbo.github.io/inborutils/reference/gbif_species_name_match.html) is not needed anymore as rgbif provides this functionality via function [`name_backbone_checklist`](https://docs.ropensci.org/rgbif/reference/name_backbone_checklist.html).

Worth to test this and in case we are 100% sure, it is maybe worth to first deprecate the function for a while before removing it. What the others think about it?

**Comment by peterdesmet** [comment]
I support deprecation. Might be good to provide an example of how to adapt current workflows that rely on the function.

**Comment by damianooldoni** [comment]
Yes! Good idea. Planning to update the tutorial about GBIF match as well.
