### ISSUE TITLE
bug in request_species_information

### ISSUE THREAD

**Issue by DimEvil** [inbo/inborutils#28]
request_species_information generates many warnings on unequal factor levels and makes R hang

'Unequal factor levels: coercing to characterbinding character and factor vector, coercing into character vectorbinding character and factor vector, coercing into character vectorUnequal factor levels: coercing to characterbinding character and factor vector, coercing into character vectorbinding character and factor vector, coercing into character vectorUnequal factor levels'

**Comment by stijnvanhoey** [comment]
Fixed by 1c8ff5da364affd900df7818497521102c97a723
