### ISSUE TITLE
Add examples to documentation of all functions

### ISSUE THREAD

**Issue by damianooldoni** [inbo/inborutils#34]
As I see efforts are taken to make this repository as documented as possible (https://github.com/inbo/inborutils/pull/33), I suggest to add examples in Roxygen documentation to as many functions as possible. Personally I use examples in documentation a lot, so I find them a nice-to-have section. We did it for the last function, `csv_to_sqlite()`. Why not doing it gradually for all the other ones? What do you think about? Obviously I can help.

**Comment by ThierryO** [comment]
Good idea. Try to make tiny examples that take only a split second to run, as all examples are run during R CMD Check. If the examples really need some time, then wrap them in a `\dontrun{}`. In that case R CMD Check will ignore them.

**Comment by damianooldoni** [comment]
Thanks @ThierryO for your tips. I will do it via branch and PR.

**Comment by hansvancalster** [comment]
Something to discuss with @inbo/bmk

**Comment by hansvancalster** [comment]
closed #109
