### ISSUE TITLE
Improve function names for consistency reason

### ISSUE THREAD

**Issue by damianooldoni** [inbo/inborutils#39]
This package contains some very useful functions to read datafiles from KMI, KNMI, Google (MOW data)...

I notice that the functions could be more consistently named. The functions are named as follows:

1. `read_kmi_data()`
2. `read_kml_file()`
3. `read_mow_data()`
4. `read_knmi_rainfall()`

An idea: what if we rename them by using the suffix `_file` for all functions? 

1. `read_kmi_file()`
2. `read_kml_file()`
3. `read_mow_file()`
4. `read_knmi_rainfall_file()`

@stijnvanhoey: what do you think about it? Thanks.

**Comment by peterdesmet** [comment]
I like consistency! But we could maybe even drop the `_file` (cf. `read_csv`):

1. `read_kmi()`
2. `read_kml()`
3. `read_mow()`
4. `read_knmi()` (unless we expect read functions for other data than`rainfall`)

**Comment by stijnvanhoey** [comment]
Good point! Certainly ok with dropping the `file`. 

With respect to knmi data, I'm not really sure if is would be more beneficial to provide a single function for all types of variables or rather split them, but as we currently only support rainfall, we can as well drop it.

**Comment by florisvdh** [comment]
I believe that KNMI also distributes evapotranspiration measurement data. These are crucial input in geohydrological analyses, beside precipitation measurements. But maybe you cover that already in the same function? If not, best to distinguish both.

You should speak about 'precipitation' instead of 'rainfall' - hey that's longer! - because that's what is covered. Snow, hail, you name it.

**Comment by stijnvanhoey** [comment]
I just checked, there is a specific difference between `read_kml` and the others. `kml` is actually refering to the file format `kml`, whereas the others are mentioning the data provider (organisation, e.g. kmi, knmi, mow,...) the data is coming from. As such, the difference between `_data` and `file` was made deliberately.

Still, to be consistent: `read_knmi_rainfall` should be `read_knmi_data` (data from the organisation knmi).

**Comment by damianooldoni** [comment]
This issue has been solved by #40
