### ISSUE TITLE
Groundwater functions

### ISSUE THREAD

**Issue by florisvdh** [inbo/inborutils#46]
Would it make sense to add the below (yet to be made) functions to `inborutils`, related to filtering groundwater data (with focus on Watina)?

An alternative is to put them in a separate package, so what is the advice here?

Current ideas regarding functions (be welcome and suggest improvements):

- concerning XG3 data:
  - `groundw_read_xg3()`: connects to database, reads necessary tables and returns combined dataset of LG3, HG3 and VG3, applying selection criteria of the user (filterdepth, start- and endyear, optional spatial mask) as well as the specified datatype (absolute/relative values (mTAW or not); truncation or not of values at soil surface)
  - `groundw_selectlocs_xg3()`: selects locations from a given dataset (formatted as returned by `groundw_read_xg3()`), according to user-specified _quality criteria_. The user also chooses the (combination of) XG3-type (LG3, HG3, VG3) to which the criteria are to be applied. In order to get the observed values to test these criteria, it calls two evaluation functions, which can be used on their own as well:
    - `groundw_evallocs_xg3avail()`: returns characteristics of each site (first, last and number of years with the requested XG3 available)
    - `groundw_evalseries_xg3()`: uses a user-specified criterium `maxgap` which defines an "xg3-series": i.e. a multiyear series of XG3 values (at 1 location), as long as possible but with gaps (nr of consecutive years without XG3) not exceeding a specified value (can be zero). It then returns for each xg3-series: start, end, total nr of years, nr of years with XG3 available (absolute & relative), deviation from uniform distribution, relative temporal variation, relative error margin in estimating the 6-yearly temporal mean.
- concerning chemistry data: similar to XG3:
  - `groundw_read_chem()`, including a specific selection criterion on electroneutrality
  - `groundw_selectlocs_chem()`, including specification of the chemical variables for which the _criteria_ are to be fulfilled (default: any present variable is good enough). Calls one evaluation function:
    - `groundw_evallocs_chemavail()`: similar to `groundw_evallocs_xg3avail()`

@stijnvanhoey @fredericpiesschaert @hansvancalster @ToonVanDaele @cecileherr @w-jan @DriesAdriaens @maudraman @mathiaswackenier

**Comment by maudraman** [comment]
Yes I think it makes sense. According to me it is important to make good agreements about the position of these functions in order to find them easily.
If there's a clear link with N2000 then it should be in the N2kutils. If not, it should be situated in a more groundwater related map in inboutils?

**Comment by ThierryO** [comment]
Consider creating a dedicated package if it either requires Watina to work or can be used more generic by others handling similar data.

**Comment by florisvdh** [comment]
OK, I suggest to put these functions in a new R-package '`watina`'.

**Comment by stijnvanhoey** [comment]
With having the connect to inbo database function (see https://github.com/inbo/inborutils/pull/47) available  and currently only having 4 to 5 new functions in scope, I would opt for including them into the inborutils package and provide a consistent naming, e.g. `watina_*` . It will them group together by name  when using  `inborutils` + `TAB`.

Later migration towards a separate package is still possible and not so difficult and only relevant when more functions are included, e.g. specific visualisations,...

**Comment by peterdesmet** [comment]
I agree with Stijn to keep in inborutils.

**Comment by ThierryO** [comment]
Keeping this in inborutils has several downsides
- Smaller, dedicated packages are easier to maintain
- You have a long list of unneeded dependencies
- inborutils will be upgraded without changes to the watina function. A dedicated watina package makes it easier to document with version of the code is used (the version number will only change when watina functions change).

**Comment by stijnvanhoey** [comment]
All valid and correct __technical__ points, but make sure there is someone to actually write those functions _now_ and maintain those package(s) _in the future_. So, from a __practical/organisational__ point of view (and context of INBO), it could(!) be easier to have the `inborutils` as main effort instead of keeping a variety of very small packages consistent in setup/.... 

That said, just go for `watina` package if you're up to it and many code-kudos from my side!

**Comment by florisvdh** [comment]
Closing this issue, as a package `watina` is [under development](https://github.com/inbo/watina/pull/3).
