### ISSUE TITLE
Guess projection error

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/inborutils#5]
When executing a guess projection I get the following error:

Error in .check_names_df(x, i) : object 'X' not found
Called from: .check_names_df(x, i)
dit krijg ik dan als callback
function (x, j) 
{
 if (is.character(j) && any(wrong <- !j %in% names(x))) {
   names <- j[wrong]
   stop(sprintf("undefined columns: %s", paste(names, collapse = ", ")))
 }
}

**Comment by stijnvanhoey** [comment]
Make sure you provide the column names of the coordinates as a string (set of characters), e.g. `"my_x_coordinate_column"`
For example:

```
guess_projection(mydframe, "X-coordinaat", "Y-coordinaat", belgium = TRUE))
```

**Comment by stijnvanhoey** [comment]
If you get the updated code, you will have an improved check for the inputs available, thanks to Thierry
