### ISSUE TITLE
Use the @family tag in Roxygen documentation

### ISSUE THREAD

**Issue by ThierryO** [inbo/inborutils#51]
Tag similar functions with `#' @family keyword`. This will automatically add a `seealso` section in the helpfiles. And you can use `has_concept("keyword")` in the `pkgdown.yml`. Which would make the pkgdown website easier to maintain.

For an example see https://github.com/ropensci/git2rdata/blob/master/_pkgdown.yml and https://github.com/ropensci/git2rdata/blob/master/R/write_vc.R

**Comment by hansvancalster** [comment]
Good idea. I suggest we start using this approach each time a new function is added. 
For the functions that are already part of the package I will make a separate PR.

**Comment by hansvancalster** [comment]
Still to do. Maybe something we can do with @inbo/bmk if I have not done it before.

**Comment by hansvancalster** [comment]
closed #109
