### ISSUE TITLE
Release maintenance

### ISSUE THREAD

**Issue by florisvdh** [inbo/inborutils#54]
The latest release dates from 9 Dec 2017, while much work has since been done.

I suggest to (more often) release a new version which can then be added to the [INBO drat repo](https://inbo.github.io/drat/), which is set as a repo in the R installations at INBO (@ThierryO), see `getOption("repos")`. This practice would prevent installation of the old version of `inborutils` when a user just runs `install.packages("inborutils")` instead of `remotes::install_github("inbo/inborutils")` - which happens too often. Also, better maintenance of version numbering would allow reverse-dependent packages to set sensible requirements on minimum version numbers of the inborutils package.

@hansvancalster , @peterdesmet can you plan this in relation to pending pull requests? (I don't know whether they need to be handled first; it's not needed for me.) In short this requires updating the DESCRIPTION file and adding a git tag such as `0.0.2` to the commit that defines the specific release.

**Comment by peterdesmet** [comment]
For versioning I would follow http://r-pkgs.had.co.nz/description.html#version. We have been using it for bioRad and it works really well. Here's the conclusion (especially for pull requests): https://github.com/adokter/bioRad/issues/149#issuecomment-424757618

Basically:

- Release often to master (but make sure checks pass) and use dev version number: `0.1.0.9xxx` with `xxx` the pull request number.
- If we feel confident about a version, bump version number to minor version `0.2.0` or mayor version `1.0.0` (for mayor changes) and create a GitHub release.
- `0.1.x` versions are only for hotfixes and patches

So, to start, we would have to bump the current version from `0.0.1` to `0.1.0`.

**Comment by hansvancalster** [comment]
I agree, that is a very good way of versioning. I have one pending PR #53 that I would like to see merged before we bump to `0.1.0` (probably today).  I am happy to do what's needed for the version numbering after the merge (but not sure if I have the rights to do so).

**Comment by peterdesmet** [comment]
👍 Version updates can be done in DESCRIPTION. If you don’t have the rights (and even if you do), you can do a pull request.

The next PR (with new functionality) should update the version to 0.1.0.9xxx

**Comment by florisvdh** [comment]
@peterdesmet thanks for providing an elaborated standard for this. Great idea to integrate the PR numbers into 9xxx, I'll implement it elsewhere. Maybe you can make a PR on this way of [versioning in the next](https://r-pkgs.org/description.html#version) R-packages book?

When releasing a new version, I think one should also add an extra commit to start the next _dev_ version `x.y.z.9000`, in order to avoid that further commits will be made that still have the release's version number (other people may/will forget to change the version number). An example of this approach is [here](https://github.com/inbo/n2khab/pull/6).

**Comment by peterdesmet** [comment]
Version number has been updated: what PR do we still want to include in `0.1.0`?

**Comment by hansvancalster** [comment]
I think PR #57 is ready and can also go into `0.1.0`. Or as @damianooldoni suggested `0.1.1`.

**Comment by peterdesmet** [comment]
Ok, that one is now merged. Note that we do not use patch updates, so it stays at `0.1.0` for now. Any other PRs that need to be merged in this version?

**Comment by florisvdh** [comment]
> it stays at 0.1.0 for now

@peterdesmet please clarify: do you mean that several commits will carry version number `0.1.0` in `DESCRIPTION`?

- should the next commits building onto master not use `0.1.0.9000` now? That would comply with going to `0.1.1` at some point in the future (which is not necessarily the next PR merge).
- or do you mean that PR #57 will still carry `0.0.1.9xxx`? That would lead to demoting master's version number after merging. `0.0.1.9xxx` < `0.1.0`
- or perhaps you do allow `0.1.0` in master for a longer time (does not resolve previous point however) while defining the released version by a tag.

**Comment by peterdesmet** [comment]
> should the next commits building onto master not use 0.1.0.9000 now?

Yes, but since we're still starting, **I wanted to know if there is still something we want to include in stable `0.1.0`**? If not, we can bump to `0.1.0.9xxx` for the next PR.

> That would comply with going to 0.1.1 at some point in the future

Normally, we will never go to `0.1.1` (that would be an urgent hotfix), but to `0.2.0`

**Comment by florisvdh** [comment]
I see, thanks. I think in the ideal situation only one commit carries a `0.1.0` number in `DESCRIPTION` so no confusion can arise about which is the stable version. We can of course add tag + release to solve that.

**Comment by florisvdh** [comment]
@peterdesmet I leave it to you whether you still want to review #50 for `0.1.0`, you can choose.

**Comment by peterdesmet** [comment]
> I think in the ideal situation only one commit carries a 0.1.0 number in DESCRIPTION so no confusion can arise about which is the stable version.

I agree, that's the ideal situation.

No, I don't have time to review that one, so I'll lock version 0.1.0 at the current commit.

**Comment by peterdesmet** [comment]
Version released: https://github.com/inbo/inborutils/releases/tag/v0.1.0

Version bumped to dev: https://github.com/inbo/inborutils/commit/21bf66a27925e6600df13c4e8a51cb4fed639a7c

**Comment by florisvdh** [comment]
On second thought, I think the guideline of inserting the PR number in the version number needs tweaking. The following case needs attention: when a PR is merged after another PR was already merged with a _higher_ number, it would lead to demoting the version number, which cannot be the purpose. E.g. it would bump a version `0.1.0.9061` to `0.1.0.9060`.

**Comment by peterdesmet** [comment]
That is correct, not sure how to fix that, but it's also bad practice to leave PR open for long. We currently have 4.
