### ISSUE TITLE
Article links do not work on pkgdown website

### ISSUE THREAD

**Issue by peterdesmet** [inbo/inborutils#55]
Reported by @hansvancalster, articles/tutorials referenced in navbar lead to 404:

- https://inbo.github.io/inborutils/articles/guess_projection.html
- https://inbo.github.io/inborutils/articles/reference/articles/gbif_name_match.html
- https://inbo.github.io/inborutils/articles/reference/articles/articles/data_loaders_examples.html

**Comment by peterdesmet** [comment]
Fixed with cac059fbef2709448ef08454dbb68f8484bf138e (see https://travis-ci.community/t/deployment-of-pages-with-r-travis-fails-with-pkgdown-when-vignettes-includes-the-current-package/2048/2 for details)

I've also used the default navbar + article section in `_pkgdown.yml`: 9a0388c501cada9be4543a9798ca5f6ba0e86a82 + added URL and issues URL: 3ab521ff53c688b2a2e3a3f0e2d3a88910e2780d

**Comment by hansvancalster** [comment]
:+1:  Thanks for fixing this!
