### ISSUE TITLE
Update package maintainer

### ISSUE THREAD

**Issue by peterdesmet** [inbo/inborutils#58]
See https://github.com/inbo/inborutils/pull/56#issuecomment-514967714:

> @damianooldoni and @peterdesmet : currently @stijnvanhoey has `role = c('aut', 'cre')` and therefore Stijn is still listed as maintainer of the package. I propose that either one of you takes over this role? If you agree who will do this, I will push the necessary changes to this branch.

**Comment by peterdesmet** [comment]
@damianooldoni and I would prefer that the maintainer of this package is someone from @inbo/bmk.

**Comment by hansvancalster** [comment]
OK, I will do it.

**Comment by peterdesmet** [comment]
:+1: you can update the description. Fine for me if this is done for `0.1.0`

**Comment by peterdesmet** [comment]
Done in #59
