### ISSUE TITLE
Add download_zenodo()

### ISSUE THREAD

**Issue by florisvdh** [inbo/inborutils#60]
@hansvancalster IMO the amazing `filemanag_zenodo()` function that you wrote earlier in the [n2khab](https://github.com/inbo/n2khab) package is not confined to n2khab-context and would probably fit better in `inborutils` as a `download_zenodo()` function that can serve any use case :wink:. It can then still be used by, or imported into `n2khab`.

Do you agree? Can you move the function out of `n2khab` into `inborutils`?

**Comment by peterdesmet** [comment]
Good suggestion @florisvdh

**Comment by hansvancalster** [comment]
I agree and opened PR #63. Closing this issue.
