### ISSUE TITLE
Fix travis builds

### ISSUE THREAD

**Issue by peterdesmet** [inbo/inborutils#73]
See https://github.com/inbo/inborutils/pull/72#issuecomment-587054024, build failed at https://travis-ci.org/inbo/inborutils/builds/651547194:

> Couldn't push the build to github.com/inbo/inborutils.git:gh-pages

**Comment by peterdesmet** [comment]
Stijn was removed as collaborator, so build using his token could nog push. Now updated to travis-ci.com and a GITHUB_TOKEN in my name. Getting a new build error.

**Comment by peterdesmet** [comment]
If I do a local `devtools::check(document = FALSE)` I get 4 failed tests @hansvancalster @damianooldoni:

```
1. Failure: input and output projections are both CRS-class (sp points) (@test-reproject_coordinates.R#143) 
2. Failure: input projections of CRS-class (sp points), output of crs-class (sf points) (@test-reproject_coordinates.R#148) 
3. Failure: input projections of crs-class (sf points), output of CRS-class (sp points) (@test-reproject_coordinates.R#153) 
4. Failure: input and output projections are both crs-class (sf points) (@test-reproject_coordinates.R#158) 
```

**Comment by peterdesmet** [comment]
The failed tests didn't occur on Travis. The repo is now migrated to travis-ci.com (rather than org) and the build is successfull: https://travis-ci.com/inbo/inborutils/builds/149329972

**Comment by damianooldoni** [comment]
Nice to hear that. :tada: 
By the way, it is still strange you get those errors locally. I have just run `devtools::check()` on the new master and I got this:
![image](https://user-images.githubusercontent.com/33662631/74681970-04410a80-51c5-11ea-811a-d4ff95bbbfef.png)

Maybe a problem of outdated packages? Maybe worth for a new issue. Just let me know if problem persists. Include in case the result of `devtools::session_info()` too.

**Comment by hansvancalster** [comment]
Thank you both for fixing this :+1:
