### ISSUE TITLE
Testing: package build fails because building vignette 'gbif_name_match' fails

### ISSUE THREAD

**Issue by florisvdh** [inbo/inborutils#87]
Testing fails ([example](https://travis-ci.com/github/inbo/inborutils/builds/169802065#L1844)) because of:

```
--- re-building ‘gbif_name_match.Rmd’ using rmarkdown
Quitting from lines 41-43 (gbif_name_match.Rmd) 
Error: processing vignette 'gbif_name_match.Rmd' failed with diagnostics:
Input must be a vector, not a `tbl_df/tbl/data.frame/gbif` object.
--- failed re-building ‘gbif_name_match.Rmd’
```

@damianooldoni can you have a look at this, I think you co-authored the vignette.

**Comment by niconoe** [comment]
Yep, struggled with that too, and I just realised it seems to depend on `dplyr` version (works with 0.8.5, fails with 1.0.0).

I suspect this has something to do with a `bind_cols()` call from `gbif_species_name_match.R`. The `dplyr` changelog mentions: `bind_cols() no longer converts to a tibble, returns a data frame if the input is a data frame.`

**Comment by damianooldoni** [comment]
By mistake I committed to master directly, a no go, I know! I am sorry about it.

**Comment by damianooldoni** [comment]
Commit reverted immediately.

**Comment by ThierryO** [comment]
@damianooldoni I've uped the protection on the master branch, so you shouldn't be able to commit to origin/master anymore.
