### ISSUE TITLE
Add GitHub action to run tests automatically

### ISSUE THREAD

**Issue by damianooldoni** [inbo/inborutils#98]
I would like to add a GitHub action to run all tests automatically. It's easy and it will notify us of problems as the one noticed by @hansvancalster in https://github.com/inbo/inborutils/pull/96#issuecomment-791246673. I cannot reproduce it as I don't get any problem with Windows 7. However, if I had that action running I could detect the issue while writing the tests.
What does @inbo/bmk think about it?

**Comment by damianooldoni** [comment]
I would also add the `pkgown.yaml` workflow that create the site automatically.

In this way all things Travis CI was doing are replaced and we don't have to get troubles like mentioned now like negative credit balance, see https://travis-ci.com/github/inbo/inborutilsproblems 
The same for appveyour: I would remove it.

But I would like to have an official  YES by @hansvancalster and @inbo/bmk before to do so.

**Comment by ElsLommelen** [comment]
Maybe you could just use [the function setup_package() from the checklist package](https://packages.inbo.be/checklist/reference/setup_package.html) and install all necessary tools at once?  ;-)

**Comment by hansvancalster** [comment]
@damianooldoni go ahead with this. I am all in favour.

**Comment by ElsLommelen** [comment]
I am in favour of replacing Travis and Appveyor with Github actions, as long as you add a windows machine to replace the Appveyor testing.  ;-)

**Comment by ThierryO** [comment]
As @ElsLommelen already pointed out, you can set it up using the checklist package. Note that is enforces a more strict standard than just R CMD check --as-cran. You can run [checkllist::check_package()](https://packages.inbo.be/checklist/reference/check_package.html) to see all checks and remarks it makes about inborutils. [checklist::setup_package()](https://packages.inbo.be/checklist/reference/setup_package.html) adds all required github actions to check according the rules set by the checklist package. The documentation still is very minimal, I'm currently working on that.

**Comment by ThierryO** [comment]
@ElsLommelen testing on windows: [check](https://github.com/inbo/checklist/blob/2030bdd096122d5a6330421037d72beac2251005/inst/package_template/check_on_different_r_os.yml#L22).

**Comment by ElsLommelen** [comment]
@ThierryO Yes, I know, my remark was just in case checklist is not used.  ;-)

**Comment by damianooldoni** [comment]
Nice! I am running and reading about `checklist`. very interesting. Nice tool, @ThierryO!

@ElsLommelen: I will try to use checklist package, sure. In any case, the nice stuff of standard Github action check is that it runs on latest Windows, Mac OS and Linux (Ubuntu)!

**Comment by ElsLommelen** [comment]
@damianooldoni And it really adds all stuff one needs for a package (if still lacking): news file, license,...  Very easy!  (As long as you use the INBO standard. ;-) )

**Comment by damianooldoni** [comment]
Yes, I see it and I love the idea. However, things done by checklist are really broader than the scope of this issue and the related branch/PR (still to write). 
I think we can do all of this in a next step. I just wanted to free @hansvancalster from Travis CI which doesn't allow him to merge and do it fast.
